# Generated by Django 2.2 on 2019-04-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('type', models.BooleanField(verbose_name='Income')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Date executed')),
                ('type', models.BooleanField(verbose_name='Income')),
                ('user_id', models.IntegerField(verbose_name='User id')),
                ('cost', models.FloatField(verbose_name='Value')),
                ('comment', models.CharField(max_length=500)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Category')),
            ],
        ),
    ]
