# Generated by Django 2.2 on 2019-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20190415_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_name',
            new_name='name',
        ),
    ]
