# Generated by Django 2.2 on 2019-04-17 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0003_auto_20190415_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='comment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.Category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
