# Generated by Django 2.2 on 2019-05-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(default='BYN', max_length=3),
        ),
    ]
